### ISSUE TITLE
Installation fails on Mac because of `find`

### ISSUE THREAD

**Issue by joom** [DmxLarchey/Kruskal-AlmostFull#4]
I am trying to install this on a Mac via opam and I ran into this problem:

```
[ERROR] The compilation of coq-kruskal-almostfull.1.0 failed at "make -j11 type".

#=== ERROR while compiling coq-kruskal-almostfull.1.0 =========================#
# context     2.1.5 | macos/arm64 | ocaml.4.14.2 | https://coq.inria.fr/opam/released#2024-06-30 14:07
# path        ~/.opam/default/.opam-switch/build/coq-kruskal-almostfull.1.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j11 type
# exit-code   2
# env-file    ~/.opam/log/coq-kruskal-almostfull-39558-b937a6.env
# output-file ~/.opam/log/coq-kruskal-almostfull-39558-b937a6.out
### output ###
# [...]
# rm -f theories/_CoqProject
# echo '-R . KruskalAfType' > theories/_CoqProject
# cat theories/CoqProject >> theories/_CoqProject
# make[1]: `Makefile' is up to date.
# coq_makefile -f _CoqProject -o Makefile.coq
# CLEAN
# rm -f Makefile.coq Makefile.coq.conf
# find \( -name "*.aux" -o -name "*.vo*" -o -name "*.glob" \) -exec rm -f {} \;
# usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
#        find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
# make[1]: *** [clean] Error 1
# make: *** [type] Error 2
```

The error is caused by `find`, since Macs use BSD find, and the `Makefile` here uses the GNU find. It's possible to install the GNU find on a Mac with `brew install findutils`, which provides a `gfind` executable.

If you're installing from source, you can change `find`s to `gfind` and that works.
If you're installing via opam, you can't do that. but you can create a shortcut to `gfind` named `find` that is seen before `/usr/bin/find`, and then it becomes possible to install it via opam.

That being said, it's probably possible to write this `Makefile` without `find`, or at least have it check which `find` to use.

**Comment by DmxLarchey** [comment]
Hi @joom,

Thank you for your interest. Indeed, the use of the `find` command is overkill in the context of the `opam` installation procedure. It was designed to clean up a `theories` sub-dir tree for a development Coq/`git` project where several branches overlap in the same sub-dir tree. Here is a excerpt of `theories/Makefile`: 

```
clean: Makefile.coq
	@+$(MAKE) -f Makefile.coq clean
	rm -f Makefile.coq Makefile.coq.conf
	find \( -name "*.aux" -o -name "*.vo*" -o -name "*.glob" \) -exec rm -f {} \;
```

The `find ...` command could simply be erased because the `@+$(MAKE) -f Makefile.coq clean` should have done the work already. 

I am going to publish an update which will look like:

```
clean: Makefile.coq
	@+$(MAKE) -f Makefile.coq clean

mrproper: clean
	rm -f Makefile.coq Makefile.coq.conf
	find \( -name "*.aux" -o -name "*.vo*" -o -name "*.glob" \) -exec rm -f {} \;
```
I am on holidays right now so I cannot really publish the thing on `coq-opam` for the next two weeks. 

Is this urgent for you? 

I could make the change in the GitHub repo. but you would have to install the package by hand. That is easy, just type `make install` for the root dir.

**Comment by DmxLarchey** [comment]
@joom: I did push an update with the proposed modification.

**Comment by DmxLarchey** [comment]
Notice that the same issue will pop up with `Kruskal-Higman`, `Kruskal-Veldman` etc 
I will do it for the other repos when you confirm me that the change was all you needed 
to get the package installed on Mac.

**Comment by joom** [comment]
Thank you for the quick response! (and sorry to disturb you on your holidays)

I had gotten around my problem with creating a shortcut to `gfind` named `find`, so this is not urgent for me. But I tested your update (installing from source) and it compiles for me.

**Comment by DmxLarchey** [comment]
The PR solving the issue has been merged on `opam`. @joom can you confirm the issue is now solved ?

**Comment by joom** [comment]
Yes, I can install from opam without `find` now, thank you!
